if: (branch = develop) OR (branch = master) OR (type = pull_request) OR (tag IS present)
sudo: required
dist: bionic
language: node_js
before_install:
  # Needed to deploy pull request and releases
  - npm i -g yarn
  - sudo apt-get -y install python-pip python-dev
  - pip install awscli --upgrade --user
cache:
  yarn: true
install:
  - yarn install
  - cd website
  - yarn install
  - cd ..
matrix:
  include:
  - if: branch =~ /^master$/ OR tag IS present
    env: NODE_ENV=development
    node_js: '12'
  - if: NOT (branch =~ /^master$/) AND NOT (tag IS present)
    env: NODE_ENV=development
    node_js: '12'
before_script:
  - cd website
  - yarn build
  - cd ..

script:
  - echo "Skip tests" # no test cases for the project

# after_success:
#   # Pull Request - Deploy it to a review environment
#   # Travis doesn't do deploy step with pull requests builds
#   - ./travis/deploy_pull_request.sh
deploy:
  - provider: s3
    bucket: $DEV_BUCKET_NAME
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    skip_cleanup: true
    local_dir: website/build/dfusion-docs
    on:
      branch: develop
      node: '12'
  - provider: s3
    bucket: $STAGING_BUCKET_NAME
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    skip_cleanup: true
    local_dir: website/build/dfusion-docs
    upload-dir: current
    on:
      branch: master
      node: '12'